package groupama.test;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Human implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Integer age;
   private java.lang.String before;
   private java.lang.String name;

   public Human()
   {
   }

   public java.lang.Integer getAge()
   {
      return this.age;
   }

   public void setAge(java.lang.Integer age)
   {
      this.age = age;
   }

   public java.lang.String getBefore()
   {
      return this.before;
   }

   public void setBefore(java.lang.String before)
   {
      this.before = before;
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public Human(java.lang.Integer age, java.lang.String before,
         java.lang.String name)
   {
      this.age = age;
      this.before = before;
      this.name = name;
   }

}