package groupama.test;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Human implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Human() {
    }

}